### ISSUE TITLE
Dependency `lasso` fails to compile on nightly toolchain

### ISSUE THREAD

**Issue by tychedelia** [mattwparas/steel#192]
See https://github.com/Kixiron/lasso/pull/45. Maintainer appears to be MIA. Looked briefly at Steel's use and it seems non-trivial to factor out.

**Comment by tychedelia** [comment]
Here's the patch from https://github.com/Kixiron/lasso/pull/45/files for anyone who needs it

```toml
[patch.crates-io]
lasso = { git = "https://github.com/lcnr/lasso/", branch = "patch-1" }
```
